export const resourcePresets = [
  {
    id: 'preset-introduction',
    kind: 'template',
    label: 'Introduction (tell me about yourself)',
    title: 'Introduction template',
    body: 'Structure a short, personal introduction.\n\nPresent - your name, where you are from and what you are studying now.\nBackground - one or two facts that shaped your decision to study abroad.\nCourse - the course and university you are applying for, and the intake.\nGoal - what you want to do after the course.\n\nKeep it to about a minute. Use your own real details, not a memorised script.',
  },
  {
    id: 'preset-why-course',
    kind: 'template',
    label: 'Why this course',
    title: 'Why this course template',
    body: 'Answer with reasons that are specific to you.\n\nPast - what you studied or did that led you to this subject.\nPresent - the skills or gaps that make this course the right next step.\nModules - name two modules you actually want to study and why.\nFuture - how the course connects to the career you described.\n\nAvoid generic lines like "it is a good course". Replace them with a detail only you could say.',
  },
  {
    id: 'preset-career-plan',
    kind: 'template',
    label: 'Career plan',
    title: 'Career plan template',
    body: 'Show a realistic plan, not a wish.\n\nTarget role - the job title you are aiming for after graduation.\nEmployers - two or three real employers or sectors in your country or region.\nSkills - the skills the course gives you that the role needs.\nFirst step - what you will do in your first months back, such as applying or networking.\n\nConnect the course modules to the role so the plan sounds researched.',
  },
  {
    id: 'preset-study-gap',
    kind: 'template',
    label: 'Study gap explanation',
    title: 'Study gap explanation template',
    body: 'Explain a gap honestly and briefly, then move forward.\n\nWhen - the period of the gap, with months and years.\nWhat - what you did during it: work, family responsibility, exams, health or preparation.\nValue - the skill or understanding you gained, in concrete terms.\nNow - why you are ready to study now and how this course fits.\n\nDo not over-apologise. A calm, factual account is more convincing than an excuse.',
  },
  {
    id: 'preset-work-experience',
    kind: 'template',
    label: 'Work experience',
    title: 'Work experience template',
    body: 'Describe work in a way that supports your study plan.\n\nRole - your job title, employer and how long you worked there.\nDuties - what you were responsible for, with one concrete example.\nSkills - the transferable skills you use, such as communication or analysis.\nLink - how this experience prepares you for the course and career.\n\nUse plain numbers and examples rather than praise or job-description wording.',
  },
  {
    id: 'preset-compare-universities',
    kind: 'research',
    label: 'Compare two universities',
    title: 'Compare two universities method',
    body: 'Build a defensible comparison using official sources.\n\n1. Pick the course at two universities and open both official course pages.\n2. Compare tuition, duration, intake and entry requirements side by side.\n3. Compare two or three modules for your specific intake.\n4. Note location, living costs and any scholarship you could apply for.\n5. Record the page and the date you checked it.\n\nBe ready to explain why your first choice won on course content, not just cost or ranking.',
  },
  {
    id: 'preset-english-requirements',
    kind: 'research',
    label: 'English language requirements',
    title: 'Check English language requirements method',
    body: 'Confirm the exact test and score your course accepts before you book.\n\n1. Open the official entry requirements page for your course and intake.\n2. Note the accepted tests and the minimum overall and component scores.\n3. Check waivers, such as study taught in English, and whether they apply to you.\n4. Confirm how and when to send the result to the university.\n\nIf your score is below the requirement, ask about pre-sessional options in writing and keep the reply.',
  },
  {
    id: 'preset-city-accommodation',
    kind: 'research',
    label: 'City and accommodation',
    title: 'City and accommodation research method',
    body: 'Research where you will actually live and what it costs.\n\n1. Use the university accommodation page for prices and contract length.\n2. Estimate private rent near campus and how you would travel to classes.\n3. Check the university cost-of-living guidance for the city.\n4. Note deposits, bills and how early rooms must be booked.\n\nAdd the figures to your budget so your finance answers match your accommodation plan.',
  },
  {
    id: 'preset-entry-deadlines',
    kind: 'research',
    label: 'Entry requirements and deadlines',
    title: 'Verify entry requirements and deadlines method',
    body: 'Keep a dated checklist so nothing is missed.\n\n1. List the academic requirement for your course and how your qualification maps to it.\n2. Note the application deadline and any earlier scholarship or deposit deadline.\n3. List required documents: transcripts, references, statement and test results.\n4. Record the official page and the date you checked it, and re-check before each interview.\n\nRequirements change between intakes, so verify rather than rely on memory.',
  },
];
