const rows = [
  [true, 'UK choice', 'Why UK?', 'Reasons for choosing the UK; alternatives considered; course quality, duration and career fit'],
  [true, 'UK choice', 'Why not Nepal?', 'Limitations of suitable courses in Nepal; career goals not met locally'],
  [true, 'UK choice', 'Why not other countries?', 'Comparison with Australia, Canada, USA and Europe; why the UK fits best'],
  [true, 'University research', 'Why this university?', 'Course and module fit; facilities; location; evidence from official sources'],
  [true, 'University research', 'Why not other universities?', 'Comparison with alternatives; why this university is the best fit'],
  [true, 'Course knowledge', 'Why this course?', 'Academic interests; skills to gain; specific modules; career connection'],
  [true, 'Career plans', 'Tell me about your career objectives.', 'Target role and industry; skills needed; how the course supports them'],
  [true, 'Accommodation', 'What have you planned for your accommodation?', 'Area; type of housing; rent; distance to campus; booking status'],
  [true, 'Finance', 'Who is going to sponsor you and how?', 'Sponsor relationship; income and savings; accessible funds; evidence'],
  [true, 'Introduction', 'Introduce yourself or describe yourself.', 'Name and background; current study or work; interest in the course'],

  [false, 'UK living', 'What are the living costs inside and outside London?', ''],
  [false, 'Work-related', 'What are the working restrictions for international students?', ''],

  [false, 'Personal / profile', 'Tell me about yourself.', ''],
  [false, 'Personal / profile', 'What is your full academic background?', ''],
  [false, 'Personal / profile', 'When did you complete your last qualification?', ''],
  [false, 'Personal / profile', 'What have you been doing since then?', ''],
  [false, 'Personal / profile', 'Do you have any study gap?', ''],
  [false, 'Personal / profile', 'Why is there a gap in your education?', ''],
  [false, 'Personal / profile', 'Do you have any work experience?', ''],
  [false, 'Personal / profile', 'Is your work experience related to your chosen course?', ''],
  [false, 'Personal / profile', 'Have you ever applied to the UK before?', ''],
  [false, 'Personal / profile', 'Have you ever had a visa refusal?', ''],
  [false, 'Personal / profile', 'Have you travelled abroad before?', ''],
  [false, 'Personal / profile', 'Do you have any relatives or friends in the UK?', ''],
  [false, 'Personal / profile', 'Why are you applying now?', ''],

  [false, 'University / course knowledge', 'What is the exact name of your university?', ''],
  [false, 'University / course knowledge', 'What is the exact name of your course?', ''],
  [false, 'University / course knowledge', 'What is the course start date?', ''],
  [false, 'University / course knowledge', 'What is the course end date?', ''],
  [false, 'University / course knowledge', 'How many modules are there?', ''],
  [false, 'University / course knowledge', 'Which modules will you study in the first semester?', ''],
  [false, 'University / course knowledge', 'Which module do you think will be the most difficult?', ''],
  [false, 'University / course knowledge', 'Which module interests you the most?', ''],
  [false, 'University / course knowledge', 'Is there a dissertation or final project?', ''],
  [false, 'University / course knowledge', 'Is there a placement?', ''],
  [false, 'University / course knowledge', 'Is the placement guaranteed?', ''],
  [false, 'University / course knowledge', 'How many teaching hours do you expect per week?', ''],
  [false, 'University / course knowledge', 'How will you be assessed?', ''],
  [false, 'University / course knowledge', 'Is assessment through exams, coursework, presentations, or projects?', ''],
  [false, 'University / course knowledge', 'What qualification will you receive after completion?', ''],

  [false, 'Academic progression', 'How is this course a progression from your previous studies?', ''],
  [false, 'Academic progression', 'Why are you studying the same level again?', ''],
  [false, 'Academic progression', 'Why are you changing your subject?', ''],
  [false, 'Academic progression', "Why did you choose a master's after your bachelor's?", ''],
  [false, 'Academic progression', 'Why do you need this qualification for your career?', ''],
  [false, 'Academic progression', 'Could you achieve the same career without this degree?', ''],
  [false, 'Academic progression', 'Why did you choose this specialization?', ''],

  [false, 'Finance', 'What is your total tuition fee?', ''],
  [false, 'Finance', 'What is your scholarship amount?', ''],
  [false, 'Finance', 'What is your tuition fee after scholarship?', ''],
  [false, 'Finance', 'How much have you already paid?', ''],
  [false, 'Finance', 'How much is still unpaid?', ''],
  [false, 'Finance', 'What is your total expected living cost?', ''],
  [false, 'Finance', 'How did you calculate your living cost?', ''],
  [false, 'Finance', 'How much money do you have available right now?', ''],
  [false, 'Finance', 'What is the source of that money?', ''],
  [false, 'Finance', 'Is any money recently deposited?', ''],
  [false, 'Finance', 'Who transferred the money?', ''],
  [false, 'Finance', 'Does your sponsor have any loans or liabilities?', ''],
  [false, 'Finance', 'How much does your family spend monthly?', ''],
  [false, 'Finance', 'How much money will remain after paying your tuition and living costs?', ''],

  [false, 'Sponsor credibility', 'Why are both your parents sponsoring you?', ''],
  [false, 'Sponsor credibility', 'What are their exact occupations?', ''],
  [false, 'Sponsor credibility', 'How long have they been working or running the business?', ''],
  [false, 'Sponsor credibility', 'What is the business name?', ''],
  [false, 'Sponsor credibility', 'Where is the business located?', ''],
  [false, 'Sponsor credibility', 'How many employees does the business have?', ''],
  [false, 'Sponsor credibility', 'What is the monthly income?', ''],
  [false, 'Sponsor credibility', 'What is the annual income?', ''],
  [false, 'Sponsor credibility', 'What tax do they pay?', ''],
  [false, 'Sponsor credibility', 'How much rental income do they receive?', ''],
  [false, 'Sponsor credibility', 'Where is the rental property located?', ''],
  [false, 'Sponsor credibility', 'Who owns it?', ''],
  [false, 'Sponsor credibility', 'How long has the property been rented?', ''],
  [false, 'Sponsor credibility', 'How is the rent received - cash or bank transfer?', ''],
  [false, 'Sponsor credibility', 'Can your parents still afford household expenses after sponsoring you?', ''],

  [false, 'Accommodation / UK living', 'Where exactly will you live?', ''],
  [false, 'Accommodation / UK living', 'Have you booked accommodation?', ''],
  [false, 'Accommodation / UK living', 'Why did you choose that area?', ''],
  [false, 'Accommodation / UK living', 'How much is the rent?', ''],
  [false, 'Accommodation / UK living', 'What is included in the rent?', ''],
  [false, 'Accommodation / UK living', 'How far is it from campus?', ''],
  [false, 'Accommodation / UK living', 'What public transport will you use?', ''],
  [false, 'Accommodation / UK living', 'What is the nearest train or bus station?', ''],
  [false, 'Accommodation / UK living', 'What is your monthly transport budget?', ''],
  [false, 'Accommodation / UK living', 'What is your monthly food budget?', ''],
  [false, 'Accommodation / UK living', 'What will you do if your accommodation falls through?', ''],
  [false, 'Accommodation / UK living', 'Do you know the weather in the city?', ''],
  [false, 'Accommodation / UK living', 'Do you know the general cost of living there?', ''],

  [false, 'UK knowledge', 'What do you know about the city where you will study?', ''],
  [false, 'UK knowledge', 'What is the nearest major city?', ''],
  [false, 'UK knowledge', 'What is the nearest airport?', ''],
  [false, 'UK knowledge', 'What attractions or landmarks are nearby?', ''],
  [false, 'UK knowledge', 'What do you know about UK culture?', ''],
  [false, 'UK knowledge', 'How will you adapt to living independently?', ''],
  [false, 'UK knowledge', 'What challenges do you expect in the UK?', ''],
  [false, 'UK knowledge', 'How will you deal with homesickness?', ''],
  [false, 'UK knowledge', 'How will you manage your time between study and daily life?', ''],

  [false, 'Work-related', 'Do you plan to work part-time?', ''],
  [false, 'Work-related', 'How many hours can international students work?', ''],
  [false, 'Work-related', 'Is part-time work your main source of funding?', ''],
  [false, 'Work-related', 'What kind of part-time job do you expect to do?', ''],
  [false, 'Work-related', 'What will you do if you cannot find a part-time job?', ''],
  [false, 'Work-related', 'Will working affect your studies?', ''],
  [false, 'Work-related', 'Are you going to the UK mainly for work?', ''],
  [false, 'Work-related', 'What is your priority: study or work?', ''],

  [false, 'Career / return-home', 'What will you do immediately after graduation?', ''],
  [false, 'Career / return-home', 'Which companies in your home country would you apply to?', ''],
  [false, 'Career / return-home', 'What salary do you expect?', ''],
  [false, 'Career / return-home', 'Why would an employer pay you that amount?', ''],
  [false, 'Career / return-home', 'What job title will you target first?', ''],
  [false, 'Career / return-home', 'Where do you see yourself in 5 years?', ''],
  [false, 'Career / return-home', 'Where do you see yourself in 10 years?', ''],
  [false, 'Career / return-home', 'Why will you return to your home country?', ''],
  [false, 'Career / return-home', 'What opportunities are available in your country?', ''],
  [false, 'Career / return-home', 'Do you have family responsibilities back home?', ''],
  [false, 'Career / return-home', 'Do you plan to start a business in the future?', ''],
  [false, 'Career / return-home', 'How will your UK degree help you compete in your local job market?', ''],

  [false, 'Comparison', 'Why not Australia?', ''],
  [false, 'Comparison', 'Why not Canada?', ''],
  [false, 'Comparison', 'Why not the USA?', ''],
  [false, 'Comparison', 'Why not Europe?', ''],
  [false, 'Comparison', 'Why not a cheaper country?', ''],
  [false, 'Comparison', 'Why not a higher-ranked university?', ''],
  [false, 'Comparison', 'Why not a cheaper university?', ''],
  [false, 'Comparison', 'Why not study online?', ''],
  [false, 'Comparison', 'Why not study the course in your home country?', ''],
  [false, 'Comparison', 'Why not choose a different intake?', ''],

  [false, 'Application process', 'Who helped you apply?', ''],
  [false, 'Application process', 'Did you use an education consultancy?', ''],
  [false, 'Application process', 'What role did the consultancy play?', ''],
  [false, 'Application process', 'Did you choose the university yourself?', ''],
  [false, 'Application process', 'Who prepared your SOP?', ''],
  [false, 'Application process', 'Did you read your own SOP?', ''],
  [false, 'Application process', 'Did anyone prepare your interview answers?', ''],
  [false, 'Application process', 'Did you submit the application yourself?', ''],
  [false, 'Application process', 'Do you know what documents were submitted?', ''],
  [false, 'Application process', 'Have you read your offer letter?', ''],
  [false, 'Application process', 'Have you read your CAS information?', ''],

  [false, 'Credibility / pressure', 'What if your visa is refused?', ''],
  [false, 'Credibility / pressure', 'What if you fail a module?', ''],
  [false, 'Credibility / pressure', 'What if you do not get a job after graduation?', ''],
  [false, 'Credibility / pressure', 'What if your sponsor cannot send more money?', ''],
  [false, 'Credibility / pressure', 'What if your university increases fees?', ''],
  [false, 'Credibility / pressure', 'What if you do not like the course after arriving?', ''],
  [false, 'Credibility / pressure', 'What if you get an opportunity to stay permanently in the UK?', ''],
  [false, 'Credibility / pressure', 'Would you still return home?', ''],
  [false, 'Credibility / pressure', 'Why should we believe you are a genuine student?', ''],
  [false, 'Credibility / pressure', 'What proves that your main purpose is education?', ''],
];
export const seedQuestions = rows.map(
  ([is_main_question, category, text, expected_concepts], i) => ({
    id: `50000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`,
    category,
    text,
    expected_concepts,
    verified_context: '',
    source_url: '',
    weight: 1,
    is_main_question,
    active: true,
    time_limit_seconds: null,
  }),
);
